apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-lsqj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-lsqj
    app.kubernetes.io/part-of: cin4s-839-0008-app
  name: devfile-sample-lsqj
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-lsqj
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-lsqj
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0008-tenant/cin4s-839-0008-app/devfile-sample-lsqj@sha256:dc32427f2fb8106adde5ce52d8708bd8c6c2099c490e90ce60229bdbd3b90000
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
